# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

commands:

  project_directory:
    description: cd to project directory
    steps:
      - run:
          name: project_directory
          command: |
            cd project-ml-microservice-kubernetes
            echo "the project directory!"
jobs:
    build:
        docker:
        # Use the same Docker base as the project
        - image: python:3.7.3-stretch

        working_directory: ~/repo

        steps:
          - checkout
          - project_directory

        # Download and cache dependencies
          - restore_cache:
              keys:
              - v1-dependencies-{{ checksum "project-ml-microservice-kubernetes/requirements.txt" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-

          - run:
              name: install dependencies
              command: |-
                python3 -m venv venv
                . venv/bin/activate
                cd project-ml-microservice-kubernetes
                make install
                # Install hadolint
                wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
          - save_cache:
              paths:
                - ./venv
              key: v1-dependencies-{{ checksum "project-ml-microservice-kubernetes/requirements.txt" }}

        # run lint!
          - run:
              name: run lint
              command: |-
                . venv/bin/activate
                cd project-ml-microservice-kubernetes
                make lint 
workflows:
  default:
    jobs:
      - build
